Project Guide
-------------
Getting the project set up and general guidance on how to work with the code
from development to deploying.

.. toctree::
    :maxdepth: 2

    foreword
    installation
    quickstart
    config
    testing
    gitflow
    deploying/index

API Reference
-------------
Information on the backend API that is used by the front end.

.. toctree::
    :maxdepth: 2

    api/index

Frontend Reference
------------------
Information on setting up and developing the frontend React application which
uses the API to display the interface on web and mobile.

.. toctree::
    :maxdepth: 2

    frontend/index

Additional Notes
----------------
Legalese and general information

.. toctree::
    :maxdepth: 2

    changelog
    license
